// SPDX-License-Identifier: BSD-2-Clause-Patent
// Exact upstream functions and branch/cleanup slices generated by Python.
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <ctype.h>
#undef NULL
#include <Uefi.h>
#include <Protocol/SimpleTextIn.h>
#include <Protocol/SimpleTextOut.h>
#define ASSERT(x) assert(x)
#define ASSERT_EFI_ERROR(x) assert(!EFI_ERROR(x))
#define DEBUG_CODE(x) do{x}while(0)
#define REPORT_STATUS_CODE(a,b) do{}while(0)
#define DEBUG(x) do{}while(0)
#define EFI_PROGRESS_CODE 0
#define BROWSER_ACTION_NONE 0
#define BROWSER_ACTION_FORM_EXIT 1
#define UI_ACTION_REFRESH_FORM 1
#define UI_ACTION_EXIT 2
#define EFI_BROWSER_ACTION_FORM_CLOSE 9
#define SystemLevel 3
#define CfReadKey 1
#define CfScreenOperation 2
#define CfExit 3
#define UiNoOperation 0
#define PcdShellPageBreakDefault 0
#define STR_SHELL_CURDIR 0
#define STR_SHELL_SHELL 0
#define PIANO_PRODUCT_PUMP_APP 4

EFI_BOOT_SERVICES *gBS;
EFI_SYSTEM_TABLE *gST;
EFI_RUNTIME_SERVICES *gRT;
static EFI_BOOT_SERVICES bs;
static EFI_SYSTEM_TABLE st;
static EFI_RUNTIME_SERVICES rt;
static EFI_SIMPLE_TEXT_INPUT_PROTOCOL input;
static EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL output;
static EFI_SIMPLE_TEXT_OUTPUT_MODE output_mode;
static BOOLEAN pending,enabled,key_ready,remote_on_wait=TRUE,allow_native_reset,request_failure;
static UINTN pumps,waits,reads,allocated,freed,event_close,commands,buffer_restores;
static UINTN front_init,front_free,reset_reminders,callbacks,discards,package_unreg;
static UINTN env_cleanup,param_cleanup,logger_cleanup,cwd_cleanup,envlist_cleanup;
static UINTN processed_input,checked_config;
static UINTN reboot_requests,native_resets,config_saves,reboot_warnings;
static VOID *display_buffer;
static UINT32 action;
static UINT64 timeout_value;
static VOID *allocations[128];
static VOID *AllocateZeroPool(UINTN n){for(UINTN i=0;i<128;++i)if(!allocations[i]){VOID *p=calloc(1,n);assert(p);allocations[i]=p;++allocated;return p;}abort();}
static VOID FreePool(VOID *p){assert(p);for(UINTN i=0;i<128;++i)if(allocations[i]==p){free(p);allocations[i]=NULL;++freed;return;}abort();}
static VOID ZeroMem(VOID *p,UINTN n){memset(p,0,n);}
static UINTN StrLen(CONST CHAR16 *s){UINTN n=0;while(s[n])++n;return n;}
static VOID StrCpyS(CHAR16 *a,UINTN n,CONST CHAR16 *b){assert(n>StrLen(b));do{*a++=*b;}while(*b++);}
static EFI_STATUS PianoProductPumpApplication(UINT32 r,UINTN b){assert(r==PIANO_PRODUCT_PUMP_APP&&b==1000);++pumps;return enabled?EFI_SUCCESS:EFI_UNSUPPORTED;}
static BOOLEAN PianoProductReturnCoreRequested(VOID){return enabled&&pending;}
static EFI_STATUS EFIAPI Wait(UINTN n,EFI_EVENT *events,UINTN *index){assert(n&&events&&index);++waits;if(enabled&&remote_on_wait){pending=TRUE;return EFI_ABORTED;}*index=0;key_ready=TRUE;return EFI_SUCCESS;}
static EFI_STATUS EFIAPI Create(UINT32 t,EFI_TPL tpl,EFI_EVENT_NOTIFY fn,VOID *ctx,EFI_EVENT *out){assert(t==EVT_TIMER&&tpl==0);*out=(VOID *)7;return EFI_SUCCESS;}
static EFI_STATUS EFIAPI SetTimer(EFI_EVENT e,EFI_TIMER_DELAY t,UINT64 delay){assert(e==(VOID *)7&&t==TimerRelative&&delay==timeout_value);return EFI_SUCCESS;}
static EFI_STATUS EFIAPI Close(EFI_EVENT e){assert(e);++event_close;return EFI_SUCCESS;}
static EFI_STATUS EFIAPI KeyRead(EFI_SIMPLE_TEXT_INPUT_PROTOCOL *self,EFI_INPUT_KEY *key){assert(self==&input&&key);++reads;if(!key_ready)return EFI_NOT_READY;*key=(EFI_INPUT_KEY){.UnicodeChar=CHAR_CARRIAGE_RETURN};key_ready=FALSE;return EFI_SUCCESS;}
static EFI_STATUS EFIAPI Query(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *self,UINTN mode,UINTN *col,UINTN *row){*col=80;*row=25;return EFI_SUCCESS;}
static EFI_STATUS EFIAPI Cursor(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *self,UINTN c,UINTN r){return EFI_SUCCESS;}
static EFI_STATUS EFIAPI Attribute(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *self,UINTN v){return EFI_SUCCESS;}
static EFI_STATUS EFIAPI Check(EFI_EVENT e){return EFI_SUCCESS;}
static EFI_STATUS EFIAPI Locate(EFI_GUID *g,VOID *r,VOID **p){*p=NULL;return EFI_NOT_FOUND;}
typedef enum{UIEventNone,UIEventKey,UIEventTimeOut,UIEventDriver,UIEventReturnCore}UI_EVENT_TYPE;
static struct{EFI_EVENT FormRefreshEvent;} form;
static typeof(form)*gFormData=&form;
static UINT64 FormExitTimeout(VOID *f){return timeout_value;}
static struct{UINT32 Action;} user;
static typeof(user)*gUserInput=&user;
static BOOLEAN gMisMatch;
static VOID InitializeListHead(LIST_ENTRY *l){l->ForwardLink=l->BackLink=l;}
static BOOLEAN IsListEmpty(CONST LIST_ENTRY *l){return l->ForwardLink==l;}
static LIST_ENTRY *GetFirstNode(CONST LIST_ENTRY *l){return l->ForwardLink;}
static LIST_ENTRY *GetNextNode(CONST LIST_ENTRY *l,CONST LIST_ENTRY *n){return n->ForwardLink;}
static BOOLEAN IsNull(CONST LIST_ENTRY *l,CONST LIST_ENTRY *n){return l==n;}
static VOID RemoveEntryList(LIST_ENTRY *n){n->ForwardLink->BackLink=n->BackLink;n->BackLink->ForwardLink=n->ForwardLink;}

typedef struct {LIST_ENTRY Link;} BUFFER_LIST;
typedef struct {LIST_ENTRY Link;} SPLIT_LIST;
typedef VOID EFI_SHELL_FILE_INFO;
typedef struct {
  CONST CHAR16 *(*GetEnv)(CONST CHAR16 *);
  EFI_STATUS (*ReadFile)(VOID *,UINTN *,VOID *);
  EFI_STATUS (*FreeFileList)(EFI_SHELL_FILE_INFO **);
  BOOLEAN (*IsRootShell)(VOID);
  EFI_EVENT ExecutionBreak;
} MOCK_SHELL_PROTOCOL;
static struct{
  MOCK_SHELL_PROTOCOL *NewEfiShellProtocol;
  struct{VOID *StdIn;}*NewShellParametersProtocol;
  EFI_EVENT UserBreakTimer;
  VOID *ImageDevPath,*FileDevPath;
  struct{CHAR16 *FileName,*FileOptions;}ShellInitSettings;
  struct{BUFFER_LIST CommandHistory;}ViewingSettings;
  BUFFER_LIST BufferToFreeList,SplitList;
  struct{BOOLEAN Enabled;UINTN RowCounter;}*ConsoleInfo;
  BOOLEAN PageBreakEnabled;
  EFI_HII_HANDLE HiiHandle;
}ShellInfoObject;
static CONST CHAR16*Env(CONST CHAR16 *n){return L"fs0:";}
static BOOLEAN RootShell(VOID){return TRUE;}
static VOID SaveBufferList(LIST_ENTRY *l){InitializeListHead(l);}
static VOID RestoreBufferList(LIST_ENTRY *l){++buffer_restores;}
static VOID ShellPrintHiiDefaultEx(UINTN token,EFI_HII_HANDLE h,...){ }
static EFI_STATUS RunCommand(CHAR16 *line){++commands;return EFI_SUCCESS;}
static VOID FreeBufferList(BUFFER_LIST *list){InitializeListHead(&list->Link);}
static VOID CleanUpShellParametersProtocol(VOID *p){++param_cleanup;FreePool(p);}
static VOID InternalEfiShellSetEnv(CONST CHAR16 *n,VOID *v,BOOLEAN b){++cwd_cleanup;}
static VOID CleanUpShellEnvironment(VOID *p){++env_cleanup;FreePool(p);}
static VOID HiiRemovePackages(EFI_HII_HANDLE h){FreePool(h);}
static VOID ConsoleLoggerUninstall(VOID *p){++logger_cleanup;}
static VOID ShellFreeEnvVarList(VOID){++envlist_cleanup;}
static BOOLEAN ShellCommandGetExit(VOID){return FALSE;}
static UINT64 ShellCommandGetExitCode(VOID){abort();}
static EFI_STATUS FreeTab(EFI_SHELL_FILE_INFO **l){FreePool(*l);*l=NULL;return EFI_SUCCESS;}

typedef struct{VOID *FormSet,*Form;UINT32 Action;VOID *Statement;EFI_HANDLE Handle;EFI_GUID FormSetGuid;UINT16 FormId;}UI_MENU_SELECTION;
static EFI_HANDLE mCurrentHiiHandle;
static EFI_GUID mCurrentFormSetGuid,gZeroGuid,gEfiBootLogoProtocolGuid;
static UINT16 mCurrentFormId;
static BOOLEAN gExitRequired;
static BOOLEAN CompareGuid(EFI_GUID *a,EFI_GUID *b){return !memcmp(a,b,sizeof(*a));}
static VOID CopyGuid(EFI_GUID *a,EFI_GUID *b){memcpy(a,b,sizeof(*a));}
static EFI_STATUS DiscardForm(VOID *fs,VOID *f,UINTN scope){assert(scope==SystemLevel);++discards;return EFI_SUCCESS;}
static EFI_STATUS ProcessCallBackFunction(VOID *sel,VOID *fs,VOID *f,VOID *q,UINT32 which,BOOLEAN save){assert(which==EFI_BROWSER_ACTION_FORM_CLOSE&&!save);++callbacks;return EFI_SUCCESS;}
static EFI_STATUS Unregister(VOID *self,VOID *handle){assert(handle==(VOID *)2);++package_unreg;return EFI_SUCCESS;}
static struct{EFI_STATUS(*UnregisterPackageNotify)(VOID *,VOID *);}database={Unregister};
static typeof(database)*mHiiDatabase=&database;
static EFI_STATUS ActualMenu(VOID);
static EFI_STATUS DisplayForm(VOID){return ActualMenu();}
static EFI_STATUS ActualBrowserClose(UI_MENU_SELECTION *Selection);
typedef struct {struct{VOID *Buffer;}CurrentValue;}MOCK_STATEMENT;
typedef struct{MOCK_STATEMENT *SelectedStatement;struct{VOID *Buffer;UINTN BufferLen;}InputValue;}USER_INPUT;
static UI_MENU_SELECTION selection;
static UI_MENU_SELECTION *gCurrentSelection=&selection;
static VOID FreeDisplayFormData(VOID){if(display_buffer){FreePool(display_buffer);display_buffer=NULL;}}
static VOID CheckConfigAccess(VOID *fs){++checked_config;}
static EFI_STATUS ProcessUserInput(USER_INPUT *u){++processed_input;return EFI_SUCCESS;}
typedef struct MOCK_BOOT_LOGO{EFI_STATUS(*SetBootLogo)(VOID *,VOID *,UINTN,UINTN,UINTN,UINTN);}EFI_BOOT_LOGO_PROTOCOL;
static VOID EfiBootManagerConnectAll(VOID){}
static VOID EfiBootManagerRefreshAllBootOption(VOID){}
static VOID InitializeFrontPage(VOID){++front_init;}
static EFI_STATUS CallFrontPage(VOID){UI_MENU_SELECTION sel={.Action=UI_ACTION_REFRESH_FORM};return ActualBrowserClose(&sel);}
static VOID FreeFrontPage(VOID){++front_free;}
static BOOLEAN IsResetRequired(VOID){return TRUE;}
VOID EFIAPI SetupResetReminder(VOID);
VOID ActualPopupWait(EFI_INPUT_KEY *Key);
static VOID CreatePopUp(UINTN attr,EFI_INPUT_KEY *Key,...){++reset_reminders;ActualPopupWait(Key);}
static VOID EFIAPI ResetSystem(EFI_RESET_TYPE Type,EFI_STATUS Status,UINTN Bytes,VOID *Data){assert(allow_native_reset&&!enabled);++native_resets;}
static BOOLEAN PianoProductRebootManaged(VOID){return enabled;}
static EFI_STATUS PianoProductRequestReboot(VOID){++reboot_requests;if(!enabled)return EFI_UNSUPPORTED;if(request_failure)return EFI_ACCESS_DENIED;pending=TRUE;return EFI_SUCCESS;}
#define MAX_STRING_LEN 100
#define ERET(e) do{errno=(e);return -1;}while(0)
enum reboot_cmd{REBOOT_HALT,REBOOT_POWEROFF,REBOOT_RESTART,REBOOT_COLD,REBOOT_WARM,REBOOT_RECOVERY,REBOOT_FASTBOOT,REBOOT_EDL,REBOOT_DATA};
enum{BOOT_REBOOT,BOOT_HALT,BOOT_POWEROFF};
typedef struct{UINTN mode;CONST CHAR8 *key;}boot_config;
static int AsciiStriCmp(CONST char *a,CONST char *b){while(*a&&*b&&tolower((unsigned char)*a)==tolower((unsigned char)*b)){++a;++b;}return tolower((unsigned char)*a)-tolower((unsigned char)*b);}
static UINTN AsciiStrLen(CONST char *s){return strlen(s);}
static char *confd_get_string_base(CONST char *key,CONST char *item,VOID *fallback){return NULL;}
static VOID confd_save_file(VOID *path){++config_saves;}
static VOID tlog_warn(CONST char *message){++reboot_warnings;}

#include "PianoActualProductUi.h"
static MOCK_SHELL_PROTOCOL template={Env,ActualConsoleRead,FreeTab,RootShell,(VOID *)9};
static VOID reset(BOOLEAN on){
  assert(allocated==freed);enabled=on;pending=key_ready=FALSE;timeout_value=100;
  pumps=waits=reads=event_close=commands=buffer_restores=0;
  front_init=front_free=reset_reminders=callbacks=discards=package_unreg=0;
  env_cleanup=param_cleanup=logger_cleanup=cwd_cleanup=envlist_cleanup=0;
  processed_input=checked_config=0;display_buffer=NULL;
  remote_on_wait=TRUE;allow_native_reset=request_failure=FALSE;reboot_requests=native_resets=config_saves=reboot_warnings=0;
  ZeroMem(&ShellInfoObject,sizeof(ShellInfoObject));
  ShellInfoObject.NewEfiShellProtocol=&template;
  InitializeListHead(&ShellInfoObject.ViewingSettings.CommandHistory.Link);
  InitializeListHead(&ShellInfoObject.BufferToFreeList.Link);InitializeListHead(&ShellInfoObject.SplitList.Link);
  user.Action=55;gMisMatch=FALSE;gExitRequired=FALSE;
}
int main(VOID){
  bs=(EFI_BOOT_SERVICES){.WaitForEvent=Wait,.CreateEvent=Create,.SetTimer=SetTimer,.CloseEvent=Close,.CheckEvent=Check,.LocateProtocol=Locate};gBS=&bs;
  rt=(EFI_RUNTIME_SERVICES){.ResetSystem=ResetSystem};gRT=&rt;
  input=(EFI_SIMPLE_TEXT_INPUT_PROTOCOL){.ReadKeyStroke=KeyRead,.WaitForKey=(VOID *)3};
  output=(EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL){.QueryMode=Query,.SetCursorPosition=Cursor,.SetAttribute=Attribute,.Mode=&output_mode};
  st=(EFI_SYSTEM_TABLE){.ConIn=&input,.ConOut=&output,.BootServices=&bs};gST=&st;
  for(action=1;action<=3;++action){
    reset(TRUE);assert(UiWaitForEvent((VOID *)3)==UIEventReturnCore&&event_close==1&&reads==0&&waits==1);
    reset(TRUE);EFI_INPUT_KEY key={.UnicodeChar=123,.ScanCode=99};assert(WaitForKeyStroke(&key)==EFI_ABORTED&&key.UnicodeChar==123&&key.ScanCode==99&&waits==1&&reads==1);
    reset(TRUE);UiEntry(TRUE);assert(pending&&front_init==1&&front_free==1&&!reset_reminders&&callbacks==1&&discards==1&&package_unreg==1&&allocated==freed&&user.Action==BROWSER_ACTION_NONE&&!gMisMatch);
    reset(TRUE);ShellInfoObject.NewShellParametersProtocol=AllocateZeroPool(sizeof(*ShellInfoObject.NewShellParametersProtocol));
    assert(DoShellPrompt()==EFI_ABORTED&&pending&&commands==0&&buffer_restores==1&&allocated==freed+1);
    ShellInfoObject.NewEfiShellProtocol=AllocateZeroPool(sizeof(template));*ShellInfoObject.NewEfiShellProtocol=template;
    ShellInfoObject.UserBreakTimer=(VOID *)8;ShellInfoObject.ImageDevPath=AllocateZeroPool(8);ShellInfoObject.FileDevPath=AllocateZeroPool(8);
    ShellInfoObject.ShellInitSettings.FileName=AllocateZeroPool(8);ShellInfoObject.ShellInitSettings.FileOptions=AllocateZeroPool(8);
    ShellInfoObject.HiiHandle=AllocateZeroPool(8);ShellInfoObject.ConsoleInfo=AllocateZeroPool(sizeof(*ShellInfoObject.ConsoleInfo));
    assert(ActualShellCleanup()==EFI_SUCCESS&&env_cleanup==1&&param_cleanup==1&&logger_cleanup==1&&cwd_cleanup==1&&envlist_cleanup==1&&allocated==freed);
  }
  reset(FALSE);assert(UiWaitForEvent((VOID *)3)==UIEventKey&&event_close==1&&!pending);
  // Legacy Null binding consumes only the genuine keyboard key.
  reset(FALSE);EFI_INPUT_KEY key={0};assert(WaitForKeyStroke(&key)==EFI_SUCCESS&&key.UnicodeChar==CHAR_CARRIAGE_RETURN&&!pending);
  reset(TRUE);pending=TRUE;assert(ActualMenu()==EFI_SUCCESS&&reads==0&&waits==0&&allocated==freed);
  reset(TRUE);pending=TRUE;USER_INPUT edit={.InputValue={AllocateZeroPool(12),12}};assert(ActualInputBranch(edit)==EFI_SUCCESS&&allocated==freed&&!processed_input&&!checked_config);
  reset(TRUE);pending=TRUE;display_buffer=AllocateZeroPool(12);MOCK_STATEMENT statement={.CurrentValue={display_buffer}};edit=(USER_INPUT){.SelectedStatement=&statement,.InputValue={display_buffer,12}};
  assert(ActualInputBranch(edit)==EFI_SUCCESS&&allocated==freed&&!processed_input&&!checked_config);
  reset(TRUE);SetupResetReminder();assert(pending&&reset_reminders==1&&waits==1&&allocated==freed);
  reset(TRUE);remote_on_wait=FALSE;SetupResetReminder();assert(pending&&reboot_requests==1&&!native_resets&&allocated==freed);
  reset(TRUE);remote_on_wait=FALSE;request_failure=TRUE;SetupResetReminder();assert(!pending&&reboot_requests==1&&!native_resets&&allocated==freed);
  reset(FALSE);allow_native_reset=TRUE;SetupResetReminder();assert(native_resets==1&&!reboot_requests&&allocated==freed);
  reset(TRUE);assert(adv_reboot(REBOOT_COLD,NULL)==0&&pending&&reboot_requests==1&&!native_resets);
  reset(TRUE);assert(adv_reboot(REBOOT_RESTART,NULL)==0&&pending&&reboot_requests==1&&!native_resets);
  reset(TRUE);request_failure=TRUE;assert(adv_reboot(REBOOT_COLD,NULL)==-1&&errno==EIO&&!pending&&!native_resets);
  for(UINTN cmd=0;cmd<=REBOOT_DATA;++cmd)if(cmd!=REBOOT_COLD&&cmd!=REBOOT_RESTART){reset(TRUE);assert(adv_reboot((enum reboot_cmd)cmd,NULL)==-1&&errno==EOPNOTSUPP&&!reboot_requests&&!native_resets);}
  reset(FALSE);allow_native_reset=TRUE;assert(adv_reboot(REBOOT_COLD,NULL)==-1&&native_resets==1&&!reboot_requests);
  reset(TRUE);boot_config boot={.mode=BOOT_REBOOT};assert(run_boot_reboot(&boot)==0&&pending&&reboot_requests==1&&config_saves==1&&!reboot_warnings&&!native_resets);
  puts("Actual patched Setup/Shell wait, UI cleanup and shared-core return paths passed for continue/reboot/boot; no reset/stop/Exit/fake keys");return 0;
}
