# SPDX-License-Identifier: MIT
# PulseAudio clients use the same left/right duplication as native clients.
stream.properties = {
    channelmix.upmix = true
    channelmix.upmix-method = simple
    channelmix.normalize = false
    channelmix.rear-delay = 0
}
