# SPDX-License-Identifier: MIT
# Ordinary stereo streams feed all four physical speaker slots, without delay.
stream.properties = {
    channelmix.upmix = true
    channelmix.upmix-method = simple
    channelmix.normalize = false
    channelmix.rear-delay = 0
}
