# SPDX-License-Identifier: MIT
# Keep one real output and input. The kernel VA capture route contains DEC0
# only and exposes one real capture channel; retain a single MONO source.
monitor.alsa.rules = [
    {
        matches = [
            { node.name = "alsa_output.platform-soc_sound-ml.HiFi__Speaker__sink" }
        ]
        actions = {
            update-props = {
                node.description = "内置扬声器"
                node.nick = "内置扬声器"
            }
        }
    }
    {
        matches = [
            { node.name = "alsa_input.platform-soc_sound-ml.HiFi__Mic__source" }
        ]
        actions = {
            update-props = {
                node.description = "内置麦克风"
                node.nick = "内置麦克风"
                audio.position = [ MONO ]
            }
        }
    }
]
