Syntax 4

SectionUseCase."HiFi" {
	File "/Qualcomm/sm8750/Xiaomi-Pad-8-Pro/HiFi.conf"
	Comment "HiFi quality Music."
}

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
